package com.telenor.cos.messaging.producers.xpath;

public class AbstractAccountXpathUnitTest extends AbstractXpathUnitTest {

    protected final static String XML_NEW_ACCOUNT = "<insert schema=\"ACCOUNT\">"
            + "<values>"
            + "<cell name=\"ACC_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"ACC_NAME\" type=\"CHAR\">Superaccount</cell>"
            + "<cell name=\"ACC_TYPE_ID\" type=\"CHAR\">NSFO</cell>"
            + "<cell name=\"ACC_STATUS_ID\" type=\"CHAR\">55</cell>"
            + "<cell name=\"ACC_PAYM_TYPE_ID\" type=\"CHAR\">888</cell>"
            + "<cell name=\"CUST_ID_PAYER\" type=\"NUMERIC\">123</cell>"
            + "<cell name=\"CUST_ID_RESP\" type=\"NUMERIC\">789</cell>"
            + "<cell name=\"E_INVOICE_ADDRESS\" type=\"CHAR\">Area 52</cell>"
            + "<cell name=\"ACC_STATUS_ID2\" type=\"CHAR\">ÅP</cell>"
            + "<cell name=\"ACC_INV_MEDIUM\" type=\"CHAR\">Letter</cell>"
            + "</values>"
            + "</insert>";

    protected final static String XML_UPDATED_ACCOUNT = "<dbStream xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://dhttm12:8000/RepraWebApp/dtds/dbeventstream.xsd\" environment=\"REP_connector.RepCondb\">"
            +  "<tran eventId=\"190:0000000863693bfe00e11f50000e00e11f5000020000a07000b5dc170000000000010003\">"
            +    "<update schema=\"ACCOUNT\">"
            +      "<values>"
            +       "<cell name=\"ACC_NAME\" type=\"VARCHAR\">176544\\DAVID345</cell>"
            +       "<cell name=\"ACC_STATUS_ID\" type=\"CHAR\"> </cell>"
            +       "<cell name=\"ACC_TYPE_ID\" type=\"CHAR\">NS</cell>"
            +       "<cell name=\"ACC_STATUS_ID2\" type=\"CHAR\">PA</cell>"
            +       "<cell name=\"ACC_INV_MEDIUM\" type=\"CHAR\">NULL</cell>"
            +       "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">Y</cell>"
            +       "<cell name=\"CUST_ID_PAYER\" type=\"NUMERIC\">6951818</cell>"
            +      "</values>"
            +      "<oldValues>"
            +       "<cell name=\"ACC_ID\" type=\"INT\">9138026</cell>"
            +       "<cell name=\"CUST_ID_PAYER\" type=\"NUMERIC\">6951817</cell>"
            +       "<cell name=\"ACC_NAME\" type=\"VARCHAR\">176544\\David345</cell>"
            +       "<cell name=\"ACC_STATUS_ID\" type=\"CHAR\">NULL</cell>"
            +       "<cell name=\"ACC_TYPE_ID\" type=\"CHAR\">NO</cell>"
            +       "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            +       "<cell name=\"ACC_STATUS_ID2\" type=\"CHAR\">ÅP</cell>"
            +       "<cell name=\"ACC_INV_MEDIUM\" type=\"CHAR\"> </cell>"
            +      "</oldValues>"
            +    "</update>"
            +  "</tran>"
            + "</dbStream>";

    protected final static String XML_LOGICAL_DELETE_CUSTOMER = "<update schema=\"ACCOUNT\">"
            + "<values>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">Y</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"ACC_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"ACC_NAME\" type=\"CHAR\">Superaccount</cell>"
            + "<cell name=\"ACC_TYPE_ID\" type=\"CHAR\">NSFO</cell>"
            + "<cell name=\"ACC_STATUS_ID\" type=\"CHAR\">55</cell>"
            + "<cell name=\"ACC_PAYM_TYPE_ID\" type=\"CHAR\">888</cell>"
            + "<cell name=\"CUST_ID_PAYER\" type=\"NUMERIC\">123</cell>"
            + "<cell name=\"CUST_ID_RESP\" type=\"NUMERIC\">789</cell>"
            + "<cell name=\"e_invoice_address\" type=\"CHAR\">Area 52</cell>"
            + "<cell name=\"ACC_INV_MEDIUM\" type=\"CHAR\">Letter</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "</oldValues>"
            + "</update>";
}