package com.telenor.cos.messaging.producers.xpath;

public class AbstractCustomerXpathUnitTest extends AbstractXpathUnitTest {
    protected final static String XML_NEW_CUSTOMER = "<insert schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">2900</cell>"
            + "<cell name=\"POSTCODE_NAME_MAIN\" type=\"CHAR\">FAGERNES</cell>"
            + "<cell name=\"ADDR_LINE_MAIN\" type=\"VARCHAR\">ELIASBAKKEN 7</cell>"
            + "<cell name=\"ADDR_CO_NAME\" type=\"VARCHAR\">SALTEN KRAFTSAMBAND AS</cell>"
            + "<cell name=\"ADDR_STREET_NAME\" type=\"VARCHAR\">ELIASBAKKEN</cell>"
            + "<cell name=\"ADDR_STREET_NUMBER\" type=\"VARCHAR\">7</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269943</cell>"
            + "</values>"
            + "</insert>";
    
    protected final static String XML_UPDATED_CUSTOMER = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269943</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">2944</cell>"
            + "<cell name=\"POSTCODE_NAME_MAIN\" type=\"CHAR\">Oslo</cell>"
            + "<cell name=\"POSTCODE_ID_PBOX\" type=\"CHAR\">LKK</cell>"
            + "<cell name=\"POSTCODE_NAME_PBOX\" type=\"CHAR\">dropbox</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"ADDR_LINE_MAIN\" type=\"CHAR\">line</cell>"
            + "<cell name=\"ADDR_CO_NAME\" type=\"CHAR\">name</cell>"
            + "<cell name=\"ADDR_STREET_NAME\" type=\"CHAR\">street</cell>"
            + "<cell name=\"ADDR_STREET_NUMBER\" type=\"CHAR\">78</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">2900</cell>"
            + "<cell name=\"POSTCODE_NAME_MAIN\" type=\"CHAR\">FAGERNES</cell>"
            + "<cell name=\"POSTCODE_ID_PBOX\" type=\"CHAR\">GH44</cell>"
            + "<cell name=\"POSTCODE_NAME_PBOX\" type=\"CHAR\">boksboks</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "<cell name=\"ADDR_LINE_MAIN\" type=\"CHAR\">line1</cell>"
            + "<cell name=\"ADDR_CO_NAME\" type=\"CHAR\">name1</cell>"
            + "<cell name=\"ADDR_STREET_NAME\" type=\"CHAR\">street1</cell>"
            + "<cell name=\"ADDR_STREET_NUMBER\" type=\"CHAR\">789</cell>"
            + "</oldValues>"
            + "</update>";

    protected final static String XML_LOGICAL_DELETE_CUSTOMER = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">Y</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">2900</cell>"
            + "<cell name=\"POSTCODE_NAME_MAIN\" type=\"CHAR\">FAGERNES</cell>"
            + "<cell name=\"POSTCODE_ID_PBOX\" type=\"CHAR\">GH44</cell>"
            + "<cell name=\"POSTCODE_NAME_PBOX\" type=\"CHAR\">boksboks</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "<cell name=\"ADDR_LINE_MAIN\" type=\"CHAR\">line1</cell>"
            + "<cell name=\"ADDR_CO_NAME\" type=\"CHAR\">name1</cell>"
            + "<cell name=\"ADDR_STREET_NAME\" type=\"CHAR\">street1</cell>"
            + "<cell name=\"ADDR_STREET_NUMBER\" type=\"CHAR\">789</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_NAME_CHANGE_CUSTOMER = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils Kayre</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_CUSTOMER_ONLY_MIDDLENAME_CHANGE = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse1</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_CUSTOMER_NAME_TO_EMPTYSTRING = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\"> </cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils Kayre</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_NAME_CHANGE_CUSTOMER_REMOVE_FIRSTNAME = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">NULL</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils Kayre</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_CUSTOMER_NAMECHANGE_FROM_NULL_TO_STRING = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">NULL</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_CUSTOMER_NAME_CHANGE_FROM_EMPTY_TO_STRING = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils Kayre</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\"> </cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse Basse</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "</oldValues>"
            + "</update>";
    
    protected final static String XML_ADRESS_CHANGE_CUSTOMER = "<update schema=\"CUSTOMER\">"
            + "<values>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">5443</cell>"
            + "</values>"
            + "<oldValues>"
            + "<cell name=\"CUST_ID\" type=\"NUMERIC\">456</cell>"
            + "<cell name=\"CUST_FIRST_NAME\" type=\"CHAR\">Nils</cell>"
            + "<cell name=\"CUST_MIDDLE_NAME\" type=\"CHAR\">Lasse</cell>"
            + "<cell name=\"CUST_LAST_NAME\" type=\"CHAR\">Olsen</cell>"
            + "<cell name=\"CUST_UNIT_NUMBER\" type=\"CHAR\">666999</cell>"
            + "<cell name=\"POSTCODE_ID_MAIN\" type=\"NUMERIC\">2900</cell>"
            + "<cell name=\"POSTCODE_NAME_MAIN\" type=\"CHAR\">FAGERNES</cell>"
            + "<cell name=\"POSTCODE_ID_PBOX\" type=\"CHAR\">GH44</cell>"
            + "<cell name=\"POSTCODE_NAME_PBOX\" type=\"CHAR\">boksboks</cell>"
            + "<cell name=\"INFO_IS_DELETED\" type=\"CHAR\">N</cell>"
            + "<cell name=\"MASTER_ID\" type=\"NUMERIC\">103269942</cell>"
            + "<cell name=\"ADDR_LINE_MAIN\" type=\"CHAR\">line1</cell>"
            + "<cell name=\"ADDR_CO_NAME\" type=\"CHAR\">name1</cell>"
            + "<cell name=\"ADDR_STREET_NAME\" type=\"CHAR\">street1</cell>"
            + "<cell name=\"ADDR_STREET_NUMBER\" type=\"CHAR\">789</cell>"
            + "</oldValues>"
            + "</update>";
}